<#
.SYNOPSIS
    NetPulse Agent Installer for Windows PCs

.DESCRIPTION
    Installs the NetPulse monitoring agent on a Windows PC.
    Creates a directory, copies agent files, configures environment,
    and optionally sets up auto-start via Task Scheduler.

.PARAMETER ServerIP
    IP address of the central Linux server running Kafka (required)

.PARAMETER PCName
    Custom name for this PC (defaults to hostname)

.PARAMETER InstallDir
    Installation directory (default: C:\NetPulse)

.PARAMETER AutoStart
    Register a Scheduled Task to start agent on boot (default: true)

.EXAMPLE
    .\install_agent.ps1 -ServerIP 192.168.1.100
    .\install_agent.ps1 -ServerIP 192.168.1.100 -PCName "LAB-PC-01"
    .\install_agent.ps1 -ServerIP 192.168.1.100 -PCName "LAB-PC-01" -AutoStart $false
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$ServerIP,

    [string]$PCName = $env:COMPUTERNAME,

    [string]$InstallDir = "C:\NetPulse",

    [bool]$AutoStart = $true
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "══════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "   NetPulse Agent Installer" -ForegroundColor Cyan
Write-Host "══════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Server IP:    $ServerIP" -ForegroundColor Yellow
Write-Host "  PC Name:      $PCName" -ForegroundColor Yellow
Write-Host "  Install Dir:  $InstallDir" -ForegroundColor Yellow
Write-Host "  Auto-Start:   $AutoStart" -ForegroundColor Yellow
Write-Host ""

# ─── 1. Create install directory ─────────────────────────────────────
Write-Host "[1/6] Creating install directory..." -ForegroundColor Green
if (-not (Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}
Write-Host "  ✓ $InstallDir" -ForegroundColor DarkGreen

# ─── 2. Copy agent files ─────────────────────────────────────────────
Write-Host "[2/6] Copying agent files..." -ForegroundColor Green
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$AgentDir = Join-Path (Split-Path -Parent $ScriptDir) "agent"

if (-not (Test-Path $AgentDir)) {
    Write-Host "  ERROR: Agent directory not found at $AgentDir" -ForegroundColor Red
    Write-Host "  Please ensure this script is in the deploy/ directory" -ForegroundColor Red
    exit 1
}

Copy-Item "$AgentDir\network_log_agent.py" "$InstallDir\" -Force
Copy-Item "$AgentDir\requirements.txt" "$InstallDir\" -Force
Write-Host "  ✓ Files copied" -ForegroundColor DarkGreen

# ─── 3. Create environment config ────────────────────────────────────
Write-Host "[3/6] Creating configuration..." -ForegroundColor Green
$EnvFile = @"
@echo off
REM NetPulse Agent Configuration
REM Generated by install_agent.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

set KAFKA_BROKER=$ServerIP`:9092
set KAFKA_TOPIC=network-logs
set PC_ID=$PCName
set COLLECT_INTERVAL=60
set LOG_FILE=$InstallDir\netpulse_agent.log
"@

$EnvFile | Out-File -FilePath "$InstallDir\config.bat" -Encoding ASCII
Write-Host "  ✓ Configuration saved to config.bat" -ForegroundColor DarkGreen

# ─── 4. Create startup batch file ────────────────────────────────────
Write-Host "[4/6] Creating startup script..." -ForegroundColor Green
$StartScript = @"
@echo off
REM NetPulse Agent Startup (auto-generated)
echo Starting NetPulse Agent...
echo   Server: $ServerIP`:9092
echo   PC ID:  $PCName

REM Load config
call "$InstallDir\config.bat"

REM Change to install directory
cd /d "$InstallDir"

REM Start agent
python network_log_agent.py
pause
"@

$StartScript | Out-File -FilePath "$InstallDir\start_agent.bat" -Encoding ASCII
Write-Host "  ✓ start_agent.bat created" -ForegroundColor DarkGreen

# ─── 5. Install Python dependencies ──────────────────────────────────
Write-Host "[5/6] Installing Python dependencies..." -ForegroundColor Green
try {
    $pythonVersion = python --version 2>&1
    Write-Host "  Found $pythonVersion" -ForegroundColor DarkGreen
} catch {
    Write-Host "  ERROR: Python is not installed or not in PATH" -ForegroundColor Red
    Write-Host "  Please install Python 3.9+ from https://python.org" -ForegroundColor Red
    exit 1
}

pip install psutil kafka-python pywin32 2>&1 | Out-Null
Write-Host "  ✓ Dependencies installed (psutil, kafka-python, pywin32)" -ForegroundColor DarkGreen

# ─── 6. Create Scheduled Task for auto-start ─────────────────────────
if ($AutoStart) {
    Write-Host "[6/6] Creating auto-start task..." -ForegroundColor Green

    $TaskName = "NetPulse Agent"

    # Remove existing task if present
    $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    }

    $Action = New-ScheduledTaskAction `
        -Execute "cmd.exe" `
        -Argument "/c `"$InstallDir\start_agent.bat`"" `
        -WorkingDirectory $InstallDir

    $Trigger = New-ScheduledTaskTrigger -AtLogon
    $Settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries `
        -DontStopIfGoingOnBatteries `
        -RestartCount 3 `
        -RestartInterval (New-TimeSpan -Minutes 1)

    $Principal = New-ScheduledTaskPrincipal `
        -UserId "SYSTEM" `
        -RunLevel Highest `
        -LogonType ServiceAccount

    Register-ScheduledTask `
        -TaskName $TaskName `
        -Action $Action `
        -Trigger $Trigger `
        -Settings $Settings `
        -Principal $Principal `
        -Description "NetPulse network monitoring agent" | Out-Null

    Write-Host "  ✓ Scheduled task '$TaskName' created (runs at logon as SYSTEM)" -ForegroundColor DarkGreen
} else {
    Write-Host "[6/6] Auto-start skipped (AutoStart=false)" -ForegroundColor Yellow
}

# ─── Summary ──────────────────────────────────────────────────────────
Write-Host ""
Write-Host "══════════════════════════════════════════" -ForegroundColor Green
Write-Host "   Installation Complete!" -ForegroundColor Green
Write-Host "══════════════════════════════════════════" -ForegroundColor Green
Write-Host ""
Write-Host "  Agent installed to: $InstallDir" -ForegroundColor Cyan
Write-Host "  Kafka broker:       $ServerIP`:9092" -ForegroundColor Cyan
Write-Host "  PC identifier:      $PCName" -ForegroundColor Cyan
Write-Host ""
Write-Host "  To start manually:" -ForegroundColor Yellow
Write-Host "    $InstallDir\start_agent.bat" -ForegroundColor White
Write-Host ""
if ($AutoStart) {
    Write-Host "  Auto-start:  ENABLED (starts at logon)" -ForegroundColor Green
} else {
    Write-Host "  Auto-start:  DISABLED" -ForegroundColor Yellow
}
Write-Host ""
